# yaml-language-server:
# $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
name: my-project
version: "0.2"
language: en
files:
  - .github/**/*.{md,txt,yaml,yml}
  - .git/COMMIT_EDITMSG
  - "*.{md,txt,yaml,yml}"
  - LICENSE
dictionaryDefinitions:
  - name: project-words
    path: ./project-words.txt
dictionaries:
  - project-words
flagWords: []
maxNumberOfProblems: 1000
ignorePaths:
  - "**/.git/!(COMMIT_EDITMSG)"
  - "**/.git/!(COMMIT_EDITMSG)/**"
  - "*-lock.yaml"
  - "*.aff"
  - "*.dic"
  - "*.gz"
  - "*.lock"
  - "*.log"
  - "*.snap"
  - "*.trie"
  - .gitignore
  - .vscode/**
  - /package.json
  - CHANGELOG.md
  - cspell.json
  - node_modules
  - snapshots/**
  - typegen.d.ts
useGitignore: true
